### ISSUE TITLE
Can't install on raspberry pi with node v12.18.4 - npm v.6.14.8

### ISSUE THREAD

**Issue by fdl333** [direktspeed/node-cctalk#2]
root@totem:/home/pi/totem# npm i node-cctalk
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/node-cctalk - Not found
npm ERR! 404
npm ERR! 404  'node-cctalk@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-25T14_55_45_677Z-debug.log
root@totem:/home/pi/totem#

**Comment by frank-dspeed** [comment]
@fdl333 npm install <git repo url> and this is using node 14+ or you need at last esm support as i have written this using ESM.
```
 npm i https://github.com/direktspeed/node-cctalk
```

**Comment by fdl333** [comment]
I get:

root@totem:/home/pi/totem#  npm i https://github.com/direktspeed/node-cctalk
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/direktspeed/node-cctalk.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-26T10_43_07_912Z-debug.log
root@totem:/home/pi/totem#

**Comment by frank-dspeed** [comment]
@fdl333 maybe you should install git on that machine i think that will help a lot once the command git works on the system the rest will work more well.
